import { ref, computed, reactive } from 'vue'
import { supabase } from '@/lib/supabase'

/**
 * useAkashicRecords Composable
 *
 * Manages the Akashic Records feature:
 * - Fetches public prayers with pagination and sorting (newest / most prayed)
 * - Fetches sinners (users currently in purgatory)
 * - Provides methods to start altruistic and intercessory prayer sessions
 *
 * Uses the same prayers table with prayer_type column to distinguish
 * between own, altruistic, and intercessory prayers.
 */
export function useAkashicRecords() {
  const publicPrayers = ref([])
  const sinners = ref([])
  const loading = ref(false)
  const sinnersLoading = ref(false)
  const error = ref(null)
  const sortBy = ref('newest') // 'newest' or 'most_prayed'
  const hasMorePrayers = ref(true)
  const currentPage = ref(0)
  const PAGE_SIZE = 20

  // Active altruistic prayer state
  const activeAltruisticPrayer = ref(null)
  const altruisticLoading = ref(false)

  /**
   * Fetch public prayers for the Akashic Records feed.
   * @param {boolean} loadMore - If true, append to existing list; otherwise reset
   */
  async function fetchPublicPrayers(loadMore = false) {
    try {
      if (!loadMore) {
        currentPage.value = 0
        publicPrayers.value = []
      }
      loading.value = true
      error.value = null

      const offset = loadMore ? currentPage.value * PAGE_SIZE : 0

      const { data, error: rpcError } = await supabase.rpc('get_public_prayers', {
        p_offset: offset,
        p_limit: PAGE_SIZE,
        p_sort_by: sortBy.value,
      })

      if (rpcError) throw rpcError

      const prayers = data || []

      if (loadMore) {
        publicPrayers.value = [...publicPrayers.value, ...prayers]
      } else {
        publicPrayers.value = prayers
      }

      hasMorePrayers.value = prayers.length >= PAGE_SIZE
      currentPage.value = loadMore ? currentPage.value + 1 : 1
    } catch (err) {
      error.value = err.message
      console.error('[useAkashicRecords] Fetch public prayers error:', err)
    } finally {
      loading.value = false
    }
  }

  /**
   * Fetch sinners (users currently in purgatory with their rejection reasons).
   */
  async function fetchSinners() {
    try {
      sinnersLoading.value = true
      error.value = null

      const { data, error: rpcError } = await supabase.rpc('get_sinners')

      if (rpcError) throw rpcError

      sinners.value = data || []
    } catch (err) {
      error.value = err.message
      console.error('[useAkashicRecords] Fetch sinners error:', err)
    } finally {
      sinnersLoading.value = false
    }
  }

  /**
   * Change sort order and refetch.
   * @param {string} sort - 'newest' or 'most_prayed'
   */
  function setSortBy(sort) {
    sortBy.value = sort
    fetchPublicPrayers(false)
  }

  /**
   * Load more prayers (pagination).
   */
  async function loadMorePrayers() {
    if (hasMorePrayers.value && !loading.value) {
      await fetchPublicPrayers(true)
    }
  }

  /**
   * Start an altruistic prayer session for someone else's prayer.
   * Creates or reactivates a prayer row with prayer_type='altruistic'.
   * @param {string} targetPrayerId - The ID of the prayer being prayed for
   * @param {string|null} responseContent - The monk's response text (for cycle timing)
   * @returns {Object} The altruistic prayer data including id
   */
  async function startAltruisticPrayer(targetPrayerId, responseContent = null) {
    try {
      altruisticLoading.value = true
      error.value = null

      const { data, error: rpcError } = await supabase.rpc('start_altruistic_prayer', {
        p_target_prayer_id: targetPrayerId,
        p_response_content: responseContent,
      })

      if (rpcError) throw rpcError

      // Fetch the full prayer record so usePrayerCounter can use it
      const { data: prayerData, error: fetchError } = await supabase
        .from('prayers')
        .select('*')
        .eq('id', data.id)
        .single()

      if (fetchError) throw fetchError

      activeAltruisticPrayer.value = prayerData
      return { ...data, prayer: prayerData }
    } catch (err) {
      error.value = err.message
      console.error('[useAkashicRecords] Start altruistic prayer error:', err)
      throw err
    } finally {
      altruisticLoading.value = false
    }
  }

  /**
   * Start an intercessory prayer session for a sinner.
   * The response_content is generated by the pray-for-sinner Edge Function first.
   * @param {string} sinnerId - The ID of the sinner being prayed for
   * @param {string} responseContent - The monk-generated intercessory prayer text
   * @returns {Object} The intercessory prayer data including id
   */
  async function startIntercessoryPrayer(sinnerId, responseContent) {
    try {
      altruisticLoading.value = true
      error.value = null

      const { data, error: rpcError } = await supabase.rpc('start_intercessory_prayer', {
        p_target_sinner_id: sinnerId,
        p_response_content: responseContent,
      })

      if (rpcError) throw rpcError

      // Fetch the full prayer record so usePrayerCounter can use it
      const { data: prayerData, error: fetchError } = await supabase
        .from('prayers')
        .select('*')
        .eq('id', data.id)
        .single()

      if (fetchError) throw fetchError

      activeAltruisticPrayer.value = prayerData
      return { ...data, prayer: prayerData }
    } catch (err) {
      error.value = err.message
      console.error('[useAkashicRecords] Start intercessory prayer error:', err)
      throw err
    } finally {
      altruisticLoading.value = false
    }
  }

  /**
   * Stop the active altruistic/intercessory prayer session.
   * @param {string} prayerId - The prayer ID to deactivate
   * @param {number} elapsedCounts - Counts to sync before deactivating
   */
  async function stopAltruisticPrayer(prayerId, elapsedCounts = 0) {
    try {
      // Sync final counts then deactivate
      const { data, error: rpcError } = await supabase.rpc('deactivate_prayer', {
        p_prayer_id: prayerId,
        p_elapsed_counts: elapsedCounts,
      })

      if (rpcError) throw rpcError

      activeAltruisticPrayer.value = null
      return data
    } catch (err) {
      error.value = err.message
      console.error('[useAkashicRecords] Stop altruistic prayer error:', err)
      throw err
    }
  }

  /**
   * Generate an intercessory prayer for a sinner using the Edge Function.
   * @param {string} sinnerId - The sinner's user ID
   * @returns {Object} The generated prayer response
   */
  async function generateSinnerPrayer(sinnerId) {
    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) throw new Error('No user logged in')

      const { data, error: fnError } = await supabase.functions.invoke('pray-for-sinner', {
        body: {
          sinner_id: sinnerId,
          user_id: user.id,
        },
      })

      if (fnError) throw fnError

      return data
    } catch (err) {
      error.value = err.message
      console.error('[useAkashicRecords] Generate sinner prayer error:', err)
      throw err
    }
  }

  /**
   * Clear the active altruistic prayer (e.g., when navigating away).
   */
  function clearActiveAltruisticPrayer() {
    activeAltruisticPrayer.value = null
  }

  return reactive({
    // State
    publicPrayers,
    sinners,
    loading,
    sinnersLoading,
    error,
    sortBy,
    hasMorePrayers,
    activeAltruisticPrayer,
    altruisticLoading,
    // Methods
    fetchPublicPrayers,
    fetchSinners,
    setSortBy,
    loadMorePrayers,
    startAltruisticPrayer,
    startIntercessoryPrayer,
    stopAltruisticPrayer,
    generateSinnerPrayer,
    clearActiveAltruisticPrayer,
  })
}