-- ======================================================================================
-- GENESIS 0: CORE PLAYER, SECTS, AND NETWORK FOUNDATION
-- ======================================================================================
-- SUPABASE AI / AGENT DIRECTIVE:
-- This is GENESIS_0. It creates the foundational tables, functions, and permissions.
-- Designed to be strictly idempotent (re-runnable).
-- ======================================================================================

BEGIN;

-- ==========================================
-- 1. MASTER NETWORK REGISTRY & UTILITIES
-- ==========================================

CREATE TABLE IF NOT EXISTS public.network_addresses (
    ip_address inet PRIMARY KEY,
    entity_type TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.network_addresses IS 'Master registry of all IP addresses to prevent cross-entity collisions.';
COMMENT ON COLUMN public.network_addresses.entity_type IS 'Table of entity owning the IP (e.g., players, sects, bots, etc)';

CREATE OR REPLACE FUNCTION public.allocate_network_address(p_entity_type TEXT) 
RETURNS inet AS $$
DECLARE
    candidate_ip inet;
BEGIN
    LOOP
        candidate_ip := (
            floor(random() * 254 + 1)::text || '.' ||
            floor(random() * 254 + 1)::text || '.' ||
            floor(random() * 254 + 1)::text || '.' ||
            floor(random() * 254 + 1)::text
        )::inet;

        BEGIN
            INSERT INTO public.network_addresses (ip_address, entity_type)
            VALUES (candidate_ip, p_entity_type);
            
            RETURN candidate_ip;
        EXCEPTION WHEN unique_violation THEN
            -- Collision detected, loop continues to try a new IP
        END;
    END LOOP;
END;
$$ LANGUAGE plpgsql VOLATILE SECURITY DEFINER;

-- ==========================================
-- 2. CORE TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS public.sects (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    ip_address inet UNIQUE REFERENCES public.network_addresses(ip_address) ON DELETE SET NULL,
    emoji TEXT NOT NULL,
    description TEXT,
    principles TEXT[] NOT NULL DEFAULT '{}',
    tone_description TEXT,
    display_order INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.sects IS 'Faction metadata that drives AI generation and game rules. Read-only for players.';
COMMENT ON COLUMN public.sects.id IS 'Slug identifier: gilded_path, holy_way, final_watch, black_tribunal';
COMMENT ON COLUMN public.sects.principles IS 'Array of faction principles used for AI prompts';

CREATE TABLE IF NOT EXISTS public.players (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE,
    ip_address inet UNIQUE NOT NULL DEFAULT public.allocate_network_address('players'),
    sect_id TEXT REFERENCES public.sects(id) ON DELETE SET NULL,
    onboarding_complete BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    
    CONSTRAINT players_username_check CHECK (
        username IS NULL OR (
            length(username) >= 3 AND 
            length(username) <= 16 AND 
            username ~ '^[a-zA-Z0-9_]+$'
        )
    )
);

COMMENT ON TABLE public.players IS 'Core player data. Tracks identity, network location, and faction.';
COMMENT ON COLUMN public.players.ip_address IS 'The unique network identifier used for in-game routing and attacks.';

-- ==========================================
-- 3. INDEXES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_network_addresses_type ON public.network_addresses(entity_type);
CREATE INDEX IF NOT EXISTS idx_players_username ON public.players(username) WHERE username IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_players_sect_id ON public.players(sect_id);
CREATE INDEX IF NOT EXISTS idx_players_onboarding ON public.players(onboarding_complete) WHERE onboarding_complete = false;

-- ==========================================
-- 4. RLS POLICIES
-- ==========================================

ALTER TABLE public.network_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Network addresses are public read-only" ON public.network_addresses;
CREATE POLICY "Network addresses are public read-only"
    ON public.network_addresses FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Service role can modify network addresses" ON public.network_addresses;
CREATE POLICY "Service role can modify network addresses"
    ON public.network_addresses FOR ALL
    USING (auth.jwt()->>'role' = 'service_role')
    WITH CHECK (auth.jwt()->>'role' = 'service_role');

DROP POLICY IF EXISTS "Sects are public read-only" ON public.sects;
CREATE POLICY "Sects are public read-only"
    ON public.sects FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Service role can modify sects" ON public.sects;
CREATE POLICY "Service role can modify sects"
    ON public.sects FOR ALL
    USING (auth.jwt()->>'role' = 'service_role')
    WITH CHECK (auth.jwt()->>'role' = 'service_role');

DROP POLICY IF EXISTS "Players readable by authenticated users" ON public.players;
CREATE POLICY "Players readable by authenticated users"
    ON public.players FOR SELECT
    TO authenticated
    USING (true);

DROP POLICY IF EXISTS "Players can update own data" ON public.players;
CREATE POLICY "Players can update own data"
    ON public.players FOR UPDATE
    TO authenticated
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Players can insert own data" ON public.players;
CREATE POLICY "Players can insert own data"
    ON public.players FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = id);

-- ==========================================
-- 5. TRIGGERS
-- ==========================================

CREATE OR REPLACE FUNCTION public.create_player_on_signup()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.players (id, username, sect_id, onboarding_complete)
    VALUES (
        NEW.id,
        NULL,
        NULL,
        false
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS create_player_on_signup_trigger ON auth.users;
CREATE TRIGGER create_player_on_signup_trigger
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.create_player_on_signup();

-- ==========================================
-- 6. API / HELPER FUNCTIONS
-- ==========================================

CREATE OR REPLACE FUNCTION public.update_player_username(p_new_username TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_user_id UUID;
    v_existing TEXT;
BEGIN
    v_user_id := auth.uid();
    
    IF p_new_username IS NULL OR length(p_new_username) < 3 OR length(p_new_username) > 16 THEN
        RETURN json_build_object('success', false, 'error', 'Username must be between 3 and 16 characters');
    END IF;
    
    IF p_new_username !~ '^[a-zA-Z0-9_]+$' THEN
        RETURN json_build_object('success', false, 'error', 'Username can only contain letters, numbers, and underscores');
    END IF;
    
    SELECT username INTO v_existing FROM public.players 
    WHERE username = p_new_username AND id != v_user_id;
    
    IF v_existing IS NOT NULL THEN
        RETURN json_build_object('success', false, 'error', 'Username already taken');
    END IF;
    
    UPDATE public.players
    SET username = p_new_username, updated_at = now()
    WHERE id = v_user_id;
    
    RETURN json_build_object('success', true, 'username', p_new_username);
END;
$$;

CREATE OR REPLACE FUNCTION public.choose_player_sect(p_sect_id TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_user_id UUID;
    v_sect_exists BOOLEAN;
BEGIN
    v_user_id := auth.uid();
    
    SELECT EXISTS(SELECT 1 FROM public.sects WHERE id = p_sect_id) INTO v_sect_exists;
    
    IF NOT v_sect_exists THEN
        RETURN json_build_object('success', false, 'error', 'Invalid sect ID');
    END IF;
    
    UPDATE public.players
    SET sect_id = p_sect_id, updated_at = now()
    WHERE id = v_user_id;
    
    RETURN json_build_object('success', true, 'sect_id', p_sect_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_player_onboarding()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_user_id UUID;
    v_username TEXT;
    v_sect_id TEXT;
BEGIN
    v_user_id := auth.uid();
    
    SELECT username, sect_id INTO v_username, v_sect_id 
    FROM public.players WHERE id = v_user_id;
    
    IF v_username IS NULL OR v_username = '' THEN
        RETURN json_build_object('success', false, 'error', 'Username not set');
    END IF;
    
    IF v_sect_id IS NULL OR v_sect_id = '' THEN
        RETURN json_build_object('success', false, 'error', 'Sect not chosen');
    END IF;
    
    UPDATE public.players
    SET onboarding_complete = true, updated_at = now()
    WHERE id = v_user_id;
    
    RETURN json_build_object('success', true, 'onboarding_complete', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.get_player_status()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    v_user_id UUID;
    v_result JSON;
BEGIN
    v_user_id := auth.uid();
    
    SELECT json_build_object(
        'id', p.id,
        'username', p.username,
        'ip_address', p.ip_address,
        'sect_id', p.sect_id,
        'sect_name', s.name,
        'sect_emoji', s.emoji,
        'onboarding_complete', p.onboarding_complete
    ) INTO v_result
    FROM public.players p
    LEFT JOIN public.sects s ON p.sect_id = s.id
    WHERE p.id = v_user_id;
    
    RETURN COALESCE(v_result, json_build_object('error', 'Player not found'));
END;
$$;

CREATE OR REPLACE FUNCTION public.get_available_sects()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    RETURN (
        SELECT jsonb_agg(
            jsonb_build_object(
                'id', s.id,
                'name', s.name,
                'ip_address', s.ip_address,
                'emoji', s.emoji,
                'description', s.description,
                'principles', s.principles,
                'tone_description', s.tone_description
            )
            ORDER BY s.display_order ASC
        )
        FROM public.sects s
    );
END;
$$;

-- ==========================================
-- 7. PERMISSIONS & GRANTS
-- ==========================================

-- Table Access
GRANT ALL ON TABLE public.network_addresses TO service_role;
GRANT ALL ON TABLE public.players TO service_role;
GRANT ALL ON TABLE public.sects TO service_role;
GRANT ALL ON TABLE public.network_addresses TO supabase_admin;
GRANT ALL ON TABLE public.players TO supabase_admin;
GRANT ALL ON TABLE public.sects TO supabase_admin;
GRANT ALL ON TABLE public.network_addresses TO postgres;
GRANT ALL ON TABLE public.players TO postgres;
GRANT ALL ON TABLE public.sects TO postgres;

GRANT SELECT ON TABLE public.network_addresses TO authenticated;
GRANT SELECT ON TABLE public.players TO authenticated;
GRANT SELECT ON TABLE public.sects TO authenticated;
GRANT INSERT ON TABLE public.players TO authenticated;
GRANT UPDATE ON TABLE public.players TO authenticated;

GRANT SELECT ON TABLE public.network_addresses TO anon;
GRANT SELECT ON TABLE public.sects TO anon;

-- Function Execution
GRANT EXECUTE ON FUNCTION public.allocate_network_address(TEXT) TO service_role, postgres;
GRANT EXECUTE ON FUNCTION public.create_player_on_signup() TO service_role, postgres;

GRANT EXECUTE ON FUNCTION public.update_player_username(TEXT) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.choose_player_sect(TEXT) TO service_role, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_player_onboarding() TO service_role, authenticated;

GRANT EXECUTE ON FUNCTION public.get_player_status() TO service_role, authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_available_sects() TO service_role, authenticated, anon;

COMMIT;